### PR TITLE
Addition of mouse-play feature.

### PR DESCRIPTION
**Pull request by rabitex**
Playing by clicking around through mouse.
Fixes #12

### CODE REVIEW

**Comment by savannahar68** [comment]
Hey take a look at my PR, probably we ,can improve that thing and also come up with 2 Player mode

**Comment by rabitex** [comment]
Actually that is based on tkinter which I am not very apt with. Also I am more that halfway through on creating a menu based interface for the game.

**Comment by rabitex** [comment]
Can you please try integrating minmax algo in our python code as well. Because this AI lacks a bit and hence needs upgradation.

**Comment by savannahar68** [comment]
Is the issue fixed ? Or should I integrate the AI ?

**Comment by rabitex** [comment]
Please try implementing the algo in Pygame version too...if you can.

**Comment by RITESHMOHAPATRA** [comment]
Issue is somewhat covered . But you can optimize more. Please make a PR in
a different branch of the original repository. All the best .

**Pull request merged**
